### PR TITLE
Fix non-native fullscreen not hiding menu/dock in secondary screens

### LINKED ISSUE #7: MacVim doesn't hide menu bar in secondary display when using pre-Lion fullscreen
For description, see this comment.
https://github.com/macvim-dev/macvim/commit/b517b310559bb4c8d297f9b2dec6aa972446b504#commitcomment-10915316

### PR DESCRIPTION
**Pull request by ychin**
Previously non-native full scrren mode would only hide the menu bar and dock when used in the primary screen. This made sense in 10.7 Lion because only the primary screen would have the menu/dock. However, 10.9 Mavericks introduced a new default where each screen would now have its own space, and therefore menu bar and dock. Make non-native full screen mode aware of this and make sure to hide the menu bar and dock when it needs to.

Fix #7.

### CODE REVIEW

**Comment by amadeus** [comment]
image

I am noticing some issues with this fix when going into non-native full screen, see the above screenshot - it's like the window isnt being measure right, and is both clipped on the top, with extra spacing on the bottom

**Comment by ychin** [comment]
Just to be exact, do you only see this issue when you enter non-native fullscreen in the secondary screen? I would be surprised if that's not the case.

I have seen the issue you are reporting before and am fixing it but I only saw it *before* my PR got merged actually (my PR hides the issue on my setup), so I'm confused why it's the other way round for you. Either way, it's an old issue, so this PR mostly changes the sequence of events that cause it to happen.

**Comment by amadeus** [comment]
I have no secondary screen on this imac. This is the primary screen that is using non-native fullscreen.

**Comment by amadeus** [comment]
I do have the dock auto-hide turned on though - and this suspiciously looks to be offset around the height of the dock

**Comment by ychin** [comment]
Ah ok that's good info to know, thanks.

But yeah as I said non-native fullscreen sizing has always been pretty buggy and I'm in the middle of fixing it up and robustify it before pushing a release, so you can consider it unstable right now.

**Comment by amadeus** [comment]
Hmm - I tried going back to the old build and seeing if unchecking autohide dock fixed it - doesn't look like it. It does look like a race condition - I have the transition animation set to REALLY short/quick btw, also if I do it a bunch - I notice inconsistent differences in how it full screens. I even had one case where the left edge was offset by like 1000 pixels from the left edge...

**Comment by ychin** [comment]
Yeah there is a race condition there. As I said, the way it actually works right now is really convoluted and it's kind of a miracle that it works at all… There's a lot of back-and-forth messaging that somehow got everything to work, mostly.

Also, the fullscreen fade to black transition is going to go away too. Hope you don't miss it :)

**Comment by amadeus** [comment]
Actually - it looks very much based on window size prior to going into fullscreen: 

[video](https://cdn.discordapp.com/attachments/365662117191352320/795750776470765598/CleanShot_2021-01-04_at_12.27.29.mp4)

**Comment by ychin** [comment]
Yup, sounds like the issue I am fixing.

**Comment by ychin** [comment]
Also, just curious, why are you using non-native full screen? Is it for the speed in transition since native full screen is slow, or the fact that you don't want it to take up a different space as you can't Cmd-Tab easily?

**Comment by amadeus** [comment]
I do a lot of front end web dev, and being able to overlay browser windows while alt tabbing is really nice when popping back and forth, without losing context

**Comment by chdiza** [comment]
> Is it for the speed in transition since native full screen is slow, or the fact that you don't want it to take up a different space as you can't Cmd-Tab easily?

Both!

**Comment by ychin** [comment]
Ok @amadeus the offset issue in non-native fullscreen should be fixed. Let me know if that's not the case.

**Comment by amadeus** [comment]
Yup - appears to work great so far!

**Pull request merged**
