### PR TITLE
Fixed double width char

### PR DESCRIPTION
**Pull request by sachka**
Commeting that line in src/screen.c will fix double width icons from devicons. The guys have a huge issue opened in their repo trying to solve it, however the fix is on our side, lots of them forked macvim just to comment that line.

### CODE REVIEW

**Comment by jordwalke** [comment]
I would love it if this would be merged (assuming this is a suitable fix (I wouldn't know)).

**Comment by jordwalke** [comment]
I think it might help to resolve the travis build failure, @sachka?

**Comment by CodeMonkeyKevin** [comment]
any chance this will be merged into master anytime soon?

**Comment by splhack** [comment]
No side effect?

@sachka could you squash your diff and update that to use `# if defined(FEAT_GUI_MACVIM)` and `gui.in_use` like #651?

**Comment by CodeMonkeyKevin** [comment]
@splhack no perceived side effects thus far.

**Comment by ichizok** [comment]
I think it is not desirable to be different from upstream regarding to the behavior on TUI and thus should use `gui.in_use`.

**Comment by splhack** [comment]
merged #664

**Pull request closed without merging**
