### PR TITLE
Big Sur style toolbar icons

### PR DESCRIPTION
**Pull request by sfsam**
Updated the toolbar icons. They are template images now in order to work with light and dark mode.

macOS 10
vim10-light
vim10-dark

macOS 11
vim11-light
vim11-dark

### CODE REVIEW

**Comment by eirnym** [comment]
May I ask to add an explicit license for them?

**Comment by sfsam** [comment]
@eirnym I'm sorry, which license do you mean?

**Comment by jspiro** [comment]
>If you need a symbol that SF Symbols doesn’t provide, you can create your own. To create a custom symbol, first export a symbol that’s similar to the design you want, then use a vector-editing tool like Sketch or Illustrator to modify it. Use the result in your app as you would use the original symbol file.
https://developer.apple.com/design/human-interface-guidelines/sf-symbols/overview/

>Availability of individual symbols and features varies based on the version of the system you’re targeting. For example, when you export a new symbol from SF Symbols 3 as an SVG template and bundle it with your app, you can use it in apps that target iOS 13, Mac Catalyst 13, tvOS 13, or watchOS 6, but without the benefit of SF Symbol 3 features like Hierarchical or Palette color rendering.
They encourage remixing of their symbols, the app itself exports symbols as SVG. Apple's dev docs note for older OSes that you can use PNG, or SVG in newer OSes. Their docs also reference adding these remixes into your resources. They do not explicitly say it must be SVG when remixed, nor do they say it may explicitly be any other format. They just use SVG in their docs as a fact and leave it there.

This is ALL I can find on licenses:
>You may not use SF Symbols — or glyphs that are substantially or confusingly similar — in your app icons, logos, or any other trademark-related use. Apple reserves the right to review and, in its sole discretion, require modification or discontinuance of use of any Symbol used in violation of the foregoing restrictions, and you agree to promptly comply with any such request.

So I think we're okay to redistribute as PNG for backwards-compatibility, and we're okay to remix, as long as we don't use it in logos, etc.

**Comment by jspiro** [comment]
Screenshot 2021-12-14 at 5 35 02 PM
And for reference, today's images.

**Comment by ychin** [comment]
Ok I finally got around to merging this. Sorry for the delay! Thanks for doing the work @sfsam.

One thing I'm concerned with is that you now make all images templated, meaning they are just grayscale masks. This works well for the ones that you have submitted, but people can use their own bitmaps too and now they will be in for a surprise. I didn't want to delay merging this but I'll probably add some code to only do that for the built-in tool bar icons.

I'm working on a separate PR to allow specifying SF Symbols for tool bar and touch bar, so that should come in soon as well. I'll probably try to fix the templating issue there. Also, now that this is merged I don't see a reason to replace your icons with the SF Symbols ones, unless Apple drastically changes things up again and introduce their next "best symbols ever" that requires everyone to change their UI again. One thing that the new SF Symbol configuration is that it allows you to do something like `menu icon=pencil.line:palette ToolBar.Test <Nop>` to get the "palette" version of the symbol. I'll think about whether I want something like that for regular images as well where you can say "image.png:template" to specify that it's a templated image. But then I feel like this is kind of niche use case.

**Pull request merged**
