### PR TITLE
Add task for creating DMG installation image

### PR DESCRIPTION
**Pull request by jirutka**
I was asked by @eirnym to send PR https://github.com/b4winckler/macvim/pull/26 (that I’ve created 3 years ago) to this repository. I rewrote it to a make task, changed MacVim logo in a background image to your new shiny logo and redesigned the background a bit.

macvim

```
./configure
make macvim-dmg
```

### CODE REVIEW

**Comment by eirnym** [comment]
I like this disk image, and it has some advantages over zip:
 * checksum checking over the bundle
 * easer to search over distributives.

**Comment by eirnym** [comment]
@jirutka I prefer minimalistic background: bigger MacVim icon leads to confusion which icon I should drag into Applications folder. So if it'll be blurred enough and/or be background of "drag action", it will be better, really.

**Comment by jirutka** [comment]
@eirnym Okay, I’ll wait for reaction from @douglasdrumond and then I’ll possibly redesing the background picture a bit. I don’t want to waste my time for the second time, just 3 years later. ;)

**Comment by eirnym** [comment]
@jirutka I hope there's no problems with licences.

**Comment by jirutka** [comment]
@eirnym What licences? I took logo from #1 and as I understand it, this is the “official” MacVim logo.

**Comment by eirnym** [comment]
Tool you used is under MIT licence.

**Comment by jirutka** [comment]
Ah, that one. MIT is very permissive license, so I hope that it’s not a problem. However, I’m not a lawyer.

**Comment by eirnym** [comment]
:+1:

**Pull request merged**
