### PR TITLE
Add macligatures option

### PR DESCRIPTION
**Pull request by splhack**
Revert Preferences.nib

### CODE REVIEW

**Comment by Shirk** [comment]
Is this really a good idea? 
I placed it in the preferences below the option to enable the CoreText-Renderer which also (to my knowledge) has only a GUI option. With the CoreText-Rendere enabling ligatures won't have any effect and we'll have a vimrc-option that depends on a gui-only option.

**Comment by Shirk** [comment]
On second thought this would enable an extension to `redraw_for_cursorline` in `move.c` which in turn could remove the need for `cursorline` or `relativeline` for proper drawing..

I'm not sure if this would bend the intended use of that method too far but it could just work..

**Comment by splhack** [comment]
this is definitely good idea. I want to use Ligatures only in some source code not for all other text files. And `antialias` or other GUI options are already exists long time.

**Comment by Shirk** [comment]
@splhack - then it should also enable the CoreText-renderer or at least notify the user *why* no notifications are visible if ATSUI is used.

**Comment by splhack** [comment]
what do you mean? `antialias` option does noting in CUI. in terms of the context, `macligatures` is the exactly same. I hope someone will create a pull request to add a nice document for Ligatures support, how to get font, how to set font, how to set up gvimrc in order to render Ligatures, ...

**Comment by Shirk** [comment]
I'm not talking about the CUI I'm talking about GUI with the checkbox 'Use Core Text renderer' disabled.
If that's the case setting `macligatures` won't have any visible effect which might confuse users.
Or is there also a vimrc-option to toggle this which I'm not aware of?

Core Text Option

**Comment by splhack** [comment]
> might confuse users

Even if user uses Core Text renderer, Ligatures doesn't work with, for example, Arial font, right? Actually I confused to review Ligatures support. then I hope there is a nice document.

**Comment by Shirk** [comment]
Yes, you're right on that part - and with it being an .vimrc-option we now require a proper document explaining it. (The old checkbox had that explanation included but I'm not going to rant about that :wink: )

**Comment by Shirk** [comment]
@splhack - I'd like to contribute [this gist](https://gist.github.com/Shirk/a0d95d0a6014896aadc8)

**Comment by splhack** [comment]
@Shirk :+1: could you create a pull request?

**Comment by Shirk** [comment]
Sure.. I was thinking about how - but never mind, it would be a PR against your branch (yes, it was a *long* day).

**Comment by splhack** [comment]
no problem to create a PR against main branch!

**Comment by Shirk** [comment]
OK looking at the other mac-only gui-related options .gvimrc supports I'll say: :+1:

(Also I'll have to open another PR once yours was merged to see if I can get extended redraw code included. Having a checkable option in the backend makes things an order of magnitude easier :wink:)

**Comment by splhack** [comment]
:tada:

**Pull request merged**
