### PR TITLE
use NSTextStorage for speedups

### PR DESCRIPTION
**Pull request by DivineDominion**
Replace NSMutableAttributesString with a concrete instance of
NSTextStorage that performs optimizations when processing
attribute changes.

### CODE REVIEW

**Comment by splhack** [comment]
we need runtime check since NSTextStorage is only for macOS 10 or later, and I don't think renaming `attribString` is not absolute necessary.

**Comment by DivineDominion** [comment]
Renaming was just to clarify that it's not just a String anymore, but I'm fine with reverting that. NSTextStorage is available since 10.0, if I'm not mistaken, not 10.10, so there should be no problem.

**Comment by splhack** [comment]
oh, thank you for pointing out. I thought it was 10.10. do you have any information of the performance gain? like Instruments screenshot.

**Comment by DivineDominion** [comment]
Phew, no, sorry. Was a tip I got a few weeks ago. Can try to get a good Instruments picture with a vanilla Cocoa project to show that this is an important factor in large documents.

**Pull request merged**
