### PR TITLE
Yosemite Tab Style based of https://github.com/b4winckler/macvim/pull/45

### PR DESCRIPTION
**Pull request by splhack**

### CODE REVIEW

**Comment by jordwalke** [comment]
I just tried this out. It looks awesome. I just noticed a couple of small issues:

- When there is only one tab open, I would expect there to be no tab bar at all. This is okay as is because I could imagine a vimscript that sets `guiopts-=e` whenever there's just one tab (and `vim-airline` actually shows the tab bar even when there's only one tab so it's not unprecedented).
- When clicking the + to add a new tab, it flickers slightly.

This really makes MacVim look modernized - they look much better in full screen mode than the old tabs did. Thanks for sending this pull request.

**Comment by jordwalke** [comment]
A couple of other thoughts:
- It looks like the + icon is a bit off centered.
- I think the plus icon button should be darker than the active tab. Perhaps it should be the same color as an inactive tab. (Which would be consistent with other mac apps that I've tested).
screen shot 2015-12-28 at 1 22 14 am


That being said, I'd rather use the PR as it is than the old ugly tabs :D

**Comment by splhack** [comment]
Pull requests welcome! :blush:

make sure the base branch is `feature/yosemite-tab-style`.

**Comment by chemzqm** [comment]
I've test this PR out, the only question is why it still not get merged into master?
IMO, it looks much better than the exist tabs and I can't see any bug.

**Comment by jordwalke** [comment]
I've been using it for a while now, and there's no noticeable bugs.

**Comment by splhack** [comment]
at least I know a minor issue

screenshot 2016-01-14 10 19 54

**Comment by jordwalke** [comment]
I noticed that this effects the performance of things like `tabdo`, even when the tabs aren't shown. I understand if it effected performance only while GUI tabs are actually shown. `nerdtree-tabs` plugin is one good example of this.

**Comment by splhack** [comment]
@jordwalke could you measure the performance loss?

- Measure performance in the master branch
- `git revert --no-commit -m 1 7cdd910` and measure performance

**Comment by jordwalke** [comment]
I could measure it, but the difference is so large that I can see it visually (it takes about 500ms to do `tabdo` on all tabs - whether or not I have yosemite tabs enabled).

**Comment by jordwalke** [comment]
I would even eyeball the performance of cycling through all of the tabs at about 400ms on my Macbook 12". Here's a plugin that shows you a repro:

https://github.com/jistr/vim-nerdtree-tabs

It cycles through all of the tabs and runs some commands. With this Yosemite change, cycling through tabs is much slower. I would be okay with that, except even when you have `set guiopts-=e`, the performance is _still_ impacted. Do you know why that could be?

**Comment by jordwalke** [comment]
It could just be that on this version of the tabs, I can *see* the tabs switching when executing a `tabdo`. The performance might be the same even on older versions fwiw.

**Pull request merged**
