### PR TITLE
Update app and document icon for Yosemite

### PR DESCRIPTION
**Pull request by jasonlong**
Since it [sounds like](https://groups.google.com/forum/m/#!topic/vim_mac/-bd5RKGs8qw) @b4winckler's original repo is dead, I thought I'd submit this PR here for the updated icon I proposed in https://github.com/b4winckler/macvim/pull/44. It had strong community approval, so I'd :heart: to see this get merged.

Here is what the icon and document icons look like. Note that this PR now includes all of the filetype document icons that @jocelynmallon built.

c2091c7a-2cb8-11e4-9795-3cd7f4487061

03f5da38-2cb9-11e4-8319-e7d7e397b16a

### CODE REVIEW

**Comment by cseelus** [comment]
Awesome

**Comment by chdiza** [comment]
From the macvim mailing list, from @douglasdrumond:

> I'll follow the guidelines already stablished (for instance, once in a while someone will ask to change the icon and my answer == Björn's answer).

**Comment by kopischke** [comment]
Yeah, but this one is not a change per se, just an adjustment of the existing ones to Yosemite aesthetics. That is still unmistakably the Vim icon.

**Comment by cseelus** [comment]
The [current App Icon](https://macin.files.wordpress.com/2009/09/macvim-7-2-icon.png) is an adaption of the [original VIM logo](http://www.vim.org/logos.php) for Apples former Human Interface Guidelines regarding App Icons. 
The one proposed by @jasonlong looks like it is adapted to the current [Human Interface Guidelines for OSX](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Designing.html).

**Comment by douglasdrumond** [comment]
I'm inclined to merge this. It's not a completely new logo, it's
recognizable as Vim. I'll evaluate it as soon as possible.

Douglas Drumond

**Comment by laerador** [comment]
As a side-note: When this is merged, the wiki-section [Notes on document icons](https://github.com/macvim-dev/macvim/wiki/Building#notes-on-document-icons) should be updated to provide a new download-link to new pre-generated document icons. The entire paragraph might need to be changed, because at least for me the steps to generating the document icons have not worked since Mountain Lion.

Over at https://github.com/b4winckler/macvim/pull/44#issuecomment-53465178, @jocelynmallon provided me with pre-generated ones. maybe these could also be linked in the wiki.

**Comment by 13k** [comment]
:+1:

**Comment by eirnym** [comment]
:+1:

**Comment by jocelynmallon** [comment]
:thumbsup:

Absolutely feel free to include any/all of the pre-made icons on the wiki; @jasonlong and all you guys did the hard work in the first place.

**Comment by pityonline** [comment]
Well, I don't like the NEW icon, it's kind of 'weak'.
MacVim Icon

**Comment by cseelus** [comment]
The time of heavy dark shadows and rugged skeuomorphism in OSX-land is well over since Yosemite. 

You might try [Candybar](http://www.panic.com/blog/candybar-mountain-lion-and-beyond) or similar solutions if you really can't deal with the new [OS X Human Interface Guidelines for App Icons](https://developer.apple.com/library/mac/documentation/UserExperience/Conceptual/OSXHIGuidelines/Designing.html) though.

**Comment by pityonline** [comment]
@cseelus Of course I can customize an icon if I spend some time on it, but I really don't think a _USER_ should waste time on an ugly icon.

**Comment by kzahedi** [comment]
Aren't we all "just" users of (mac)vim? Last I checked, there was not customer service, because there are no customers. BTW, I like to new icon.

**Comment by douglasdrumond** [comment]
Although @kzahedi is right in "there's no customer service", I try to do what's better for the community. But, unfortunately, there's no way to please everyone. Since it's *Mac*Vim, the new icons didn't deviate from Vim icon and there was support for it, I decided to upgrade. Let's move forward on this and embrace the new icon.

**Pull request merged**
