### PR TITLE
Fix detection of deployment target

### PR DESCRIPTION
**Pull request by chdiza**

### CODE REVIEW

**Comment by splhack** [comment]
you should update src/configure.in as well

**Comment by chdiza** [comment]
src/configure.in already had the square brackets.

**Comment by splhack** [comment]
please take a look at https://github.com/macvim-dev/macvim/pull/117

**Comment by chdiza** [comment]
I see that, but when I made this PR, src/configure.in already had the square brackets, as you can see [here](https://github.com/macvim-dev/macvim/commit/77bf482db4660fd5e6d00dda6d65d1657c458de2)

**Pull request closed without merging**
