### PR TITLE
Hide MNU_HIDDEN_CHAR prefix from menu title if present

### PR DESCRIPTION
**Pull request by eirnym**
Closes: https://github.com/macvim-dev/macvim/issues/853

### CODE REVIEW

**Comment by ychin** [comment]
This doesn't actually fix the issue. We need to hide the menu completely, not just remove the ']' character.

**Comment by eirnym** [comment]
@ychin it opens as desired when it was requested. This is handled by vim core

**Comment by eirnym** [comment]
Implementation for Win32 has the same check

**Comment by eirnym** [comment]
I'll revisit the issue today

**Comment by ychin** [comment]
The issue that #853 is complaining about is that any menus that start with "]" need to be hidden in the menu bar. I believe MacVim still shows that at the moment. The name clean up part (which this PR is doing) is mostly for neatness in how it shows the name of the menu, but not the core functionality of what it does.

I think we need to just fix the menus with this prefix to not show up in the main menu bar. gVim / MacVim does something similar with "ToolBar." menus, and MacVim also hides "Touchbar" ones as well.

**Comment by eirnym** [comment]
Thank you, I've found these menus and updated my commit. I'm sorry for inconvenience

**Comment by eirnym** [comment]
I read the logs and don't see any test failed.

**Comment by eirnym** [comment]
@ychin Is it one of flaky tests? 
```
Failures: 
	From test_alot.vim:
	Found errors in Test_suspend():
	Caught exception in Test_suspend(): WaitFor() timed out after 5000 msec @ function RunTheTest[40]..Test_suspend[37]..Stop_shell_in_terminal[3]..WaitFor, line 4
```

**Comment by eirnym** [comment]
merged current master into my branch

**Comment by ychin** [comment]
Yes `test_suspend` is a flaky test and I need to figure out why it's so.

**Comment by ychin** [comment]
I don't think the current implementation does what Vim is supposed to do? "]" is not a substitute for "PopUp". It just hides the menu. You can then use `:popup` to pop up *any* menu including the ones you hid using `]`, or just a regular menu like "File". We shouldn't have any code that assumes "PopUp" menus have the same meaning as "]" ones.

**Comment by eirnym** [comment]
there was two reasons for this:

1) PopUp are just special hidden menus as it's documented, `]` are user-defined. I haven't found any other difference between them
2) ObjC implementation says that they follow the same logic in terms of creating and processing `NSMenu` and `NSMenuItem` objects

```objc
    // If descriptor has no parent and its not a popup (or toolbar) menu,
    // then it must belong to main menu.
```

**Comment by ychin** [comment]
Yeah sorry you are right. I misread the code.

**Pull request merged**
