### PR TITLE
Update Sparkle to 1.24.0

### PR DESCRIPTION
**Pull request by ichizok**
#1113 Sparkle 1.24.0 is compatible with Apple M1 (arm64).

### CODE REVIEW

**Comment by ychin** [comment]
Sorry for the delay. I'll try to merge this by end of week. There are a lot of files so just want to confirm on my end this is the same as the recent release.

**Comment by manchicken** [comment]
Is there any way to tweak this to support `arm64` as well? I've never done much with Sparkle, but it seems like this is going to be one of many impediments to supporting the new Apple chipsets.

**Comment by felixbuenemann** [comment]
@ichizok I can confirm this works to make MacVim master arm64 compile and run on M1 MacBook Air running macOS 11.1 Beta.

**Comment by ychin** [comment]
Ok merged. Sorry for the delay. But yes this should fix Apple Silicon building. The previous released Sparkle binary was not a universal binary, so when MacVim tries to build against it in a universal binary, it couldn't as there was not arm64 binary in Sparkle. The new version now supports that.

**Comment by markwu** [comment]
But, I still build failed macOS Catalina with Xcode 12.2.

**Comment by markwu** [comment]
I still need the patch to build macvim under homebrew. Weird.

**Comment by ychin** [comment]
Yeah Homebrew is a different issue that has to do with the way the formula works. This is more for fixing #1113 than #1115. I still need to resolve that.

**Comment by netcaf** [comment]
Hello, 
Is there any native build for downloading? I tried it with homebrew but it prompted I should install Xcode. 

Thank you.

**Comment by ychin** [comment]
@netcaf No there is no native Apple Silicon / M1 build yet, but you can use the current release under Rosetta. Is there a reason why you need a native Apple Silicon build? From what I have tried, Rosetta performance is decent enough that it should not make too big an impact.

Apple Silicon build will come out probably after the upcoming release. If you use the binary release published in https://github.com/macvim-dev/macvim/releases the automatic updater will still work and upgrade you to Apple Silicon native builds in the future.

It's currently a little tricky to push out Apple Silicon builds due to lack of CI support.

**Comment by manchicken** [comment]
I think the biggest issue is that if you’re using other arm64 binaries then macvim won’t pick those up. This means I need two versions of python3 installed, one for `vim` and one for MacVim.

~ Michael D. Stemle, Jr.

**Comment by ychin** [comment]
Yes that is correct. It does depend on where you get your Python from. For example the default Homebrew installation is still Rosetta based so if you are using that you would actually be getting the x86 version.

**Comment by netcaf** [comment]
> @netcaf No there is no native Apple Silicon / M1 build yet, but you can use the current release under Rosetta. Is there a reason why you need a native Apple Silicon build? From what I have tried, Rosetta performance is decent enough that it should not make too big an impact.
> 
> Apple Silicon build will come out probably after the upcoming release, so probably release 168. If you use the binary release published in https://github.com/macvim-dev/macvim/releases the automatic updater will still work and upgrade you to Apple Silicon native builds in the future.
> 
> It's currently a little tricky to push out Apple Silicon builds due to lack of CI support hence the delay.

@ychin  Thank you for the explanation. I have just got my MacBook m1 and is full of curiosity about the new experience. Macvim is my favorite app but it’s Ok I will try it with Rosetta.

Thank you all for your time.

**Pull request merged**
