### PR TITLE
Better bug report text

### PR DESCRIPTION
**Pull request by eirnym**
Added some information which is asked anyway, so users will see it right from the start

### CODE REVIEW

**Comment by Tiza59** [comment]
Please remove 2 typos: insatllation form -> installation from

**Comment by eirnym** [comment]
@Tiza59 thank you for pointing me to a typo

**Comment by ichizok** [comment]
@eirnym I made some changes to resolve conflict.
Would you mind rebasing in order to cleanup commits, if it's ok?

**Comment by eirnym** [comment]
@ichizok Thank you, for the help! I rebased the commit on top of the current master branch, fixing the author (I don't know how it made the "your name <you@example.com> in history!)

**Comment by ichizok** [comment]
Thank you.

**Pull request merged**
