### PR TITLE
Support guioptions 'k' flag in MacVim (2nd attempt)

### PR DESCRIPTION
**Pull request by ychin**
This re-commits and fixes the issues introduced in the previous pull request that implemented guioptions 'k' (#708). That commit was reverted in #727.

The issues it fixes:

* *Zoom button* (#724): There was an error in refactoring leading to the handler calling the wrong function.

* *Toolbar addition/removal*: Toolbar now respects the 'k' option. Toolbar is different from scrollbar and tabs because when you add/remove a toolbar in Cocoa it automatically resizes the window for you, so the implementation needs to manually un-resize the window and re-calculates the Vim view's 'lines' and 'columns' to fit.

**NOTE**: There's another issue where the last implementation broke MacVim on external monitors (#721 and #728). I do not have access to an external monitor now and can't test whether this fixes it (no USB-C adapter). I looked through the code and still couldn't figure out why the external monitor would cause issues especially if the user hasn't set `go+=k`. I will need to find an external monitor to test, but if someone can quickly try this out and sanity check it I would appreciate it.

Please do not merge yet until I can verify that the external monitor issue is fixed.

**Edit**: The external monitor issue is now fixed (e35b0a6). This PR should be OK to merge!

### CODE REVIEW

**Comment by ychin** [comment]
Just pinging @ichizok @dctucker for this PR. I'm working to fix the previous issues in my implementation for guioptions 'k', and if you have time feel free to try this out to see if this fixes the issue. As I mentioned in the PR I don't have a way to test external monitors at the moment.

**Comment by dctucker** [comment]
Unfortunately, it looks like the problem persists with this build.

**Comment by ychin** [comment]
I believe I have fixed all the issues introduced in the original implementations. Those are:

1. Zoom button not working properly (#724)
2. Opening Vim in an external monitor or opening a new Vim window in another monitor would result in broken rendering (#721, #728)
3. Tool bar not respecting `guioptions+=k`. (This one was less problematic since it didn't screw up the behavior for normal users who didn't set it)

Pinging @dctucker @ichizok again. Also @splhack if he wants to merge it. I tested this in an external monitor after the fix (yay USB-C dongle!) and couldn't reproduce it. I'm pretty confident the issue is now fixed.

**Comment by ichizok** [comment]
@ychin Thank you, I confirmed the fix about toolbar on/off with guioptions-k.

**Comment by ychin** [comment]
Is there anything else I need to do for this pull request? I am pretty sure I addressed the issues caused by the original change and I have been using the editor after my fix and they seem to work fine. I have a few additional fixes for some full screen rendering and resizing bugs but they rely on this change so wondering what I can do to get this merged. Thanks.

**Pull request merged**
