### PR TITLE
Add screenshot of MacVim in action.

### PR DESCRIPTION
**Pull request by joshuapinter**
It's a beautiful app, let's show it off!

Welcome to use this image or a different one. I just opened up the `README.md` of the repo.

Screen Shot 2019-04-25 at 8 02 08 AM

### CODE REVIEW

**Comment by chdiza** [comment]
If we want to show it off, we would need to do something better than that image;  it looks almost exactly like how using console Vim would look.

Since console Vim now has truecolor support, MacVim no longer has the advantage of having prettier colors.   To "show off" what MacVim does differently will require displaying things unique to MacVim.  E.g., each Vim window inside a tab having its own Aqua scrollbars, or the macOS-native tab bar.  (The former, however, is not very beautiful.)  But there's very little appearance-wise that is unique to MacVim these days.

Things like fullscreen and transparency and blur can also be done by the terminal emulator and therefore can be enjoyed in console Vim.

Really, just about the only remaining reasons to use MacVim rather than regular Vim are things that wouldn't show up in a screenshot.  (E.g.,  (a) the fact that you can just double-click a document instead of having to first navigate in the terminal, (b) the fact that you can use mappings involving the Cmd key, (c) the various `:macaction`s...)

**Comment by chdiza** [comment]
Also, if we add screenshots, I think they should be put on the Wiki (or the homepage https://macvim-dev.github.io/macvim/), rather than enlarging the repo with things not needed to build MacVim.

**Comment by eirnym** [comment]
I agree with @chdiza that we should show a little example of configured MacVim. 

A small GIF is better than series of screenshot images, and it's not a large file to add if it would be a single one for this goal. Also we could link it into README to show it. Wiki is required if some complex documentation is needed to be put and it can't be put inside MacVim

**Comment by ychin** [comment]
I do want to revamp the README and the wiki but been punting on it due to personal time constraints and there have been higher priority issues on MacVim to fix. The README is too spartan and would be nice for newcomers to have more information.

That said, I consider having a better layout, more general information in line with other projects (general info about the project, license info, links to releases page, how to build, etc) to be higher priority than adding a screenshot for now.

For the screenshot I think having one or two screenshot is nice for README but the one submitted here isn't quite enough I think due to the reasons already discussed. Some unique features to MacVim are easier to show off (native tab bar, scrollbars, menus, Touch Bar, integrating with window manager) than others (touch gesture support, Cmd-key bindings, macaction, support for guioptions, etc).

**Pull request closed without merging**
