### PR TITLE
Restore 10.6 support

### PR DESCRIPTION
**Pull request by rhendric**
Per comments in #173. This would replace #178 (it includes the first commit of that PR).

### CODE REVIEW

**Comment by rhendric** [comment]
@splhack, how's this?

**Comment by splhack** [comment]
cool. but the target branch is actually `fix/remove_legacy_stuff`? it seems `master`.

**Comment by rhendric** [comment]
Ohhh, you want a new PR?

**Comment by splhack** [comment]
thanks! (I thought target branch is modifiable)

**Pull request closed without merging**
