### PR TITLE
Fix Double Wide Glyph Rendering

### PR DESCRIPTION
**Pull request by jordwalke**
Applying the suggestions mentioned in this diff and tested locally.

https://github.com/macvim-dev/macvim/pull/648

### CODE REVIEW

**Comment by ichizok** [comment]
According to the style of existing code;

```diff
--- a/src/screen.c
+++ b/src/screen.c
@@ -8385,7 +8385,10 @@ screen_char(unsigned off, int row, int col)
            }
            /* not sure where the cursor is after drawing the ambiguous width
             * character */
-           screen_cur_col = 9999;
+# ifdef FEAT_GUI_MACVIM
+           if (!gui.in_use)
+# endif
+               screen_cur_col = 9999;
        }
        else if (utf_char2cells(ScreenLinesUC[off]) > 1)
            ++screen_cur_col;
```

**Comment by jordwalke** [comment]
Note: You can squash these two diffs at the time you merge the pull request. I left the two commits here so that the conversation isn't lost, but I'm aware you prefer to have the commits squashed into one (it's an option in the dropdown menu at time of merge - select Squash option).

**Comment by ichizok** [comment]
Hmm, this change makes the display of ambiguous width characters broken when `'ambiwidth'` is `double`.

Example:

Start MacVim and input `i\<C-V>u03bbabc\<Esc>` (&lambda;abc).

When `set ambiwidth=single` (default);

macvim-ambw-single

And when `set ambiwidth=double`;

Applied this PR:

macvim-ambw-double-pr

Expected (current behavior):

macvim-ambw-double

**Comment by jordwalke** [comment]
With this diff, is there ever a reason to use ambiwidth=double?

**Comment by ichizok** [comment]
Adding the condition `ambiwidth=double`. How is this?

```diff
--- a/src/screen.c
+++ b/src/screen.c
@@ -8391,7 +8391,10 @@ screen_char(unsigned off, int row, int col)
            }
            /* not sure where the cursor is after drawing the ambiguous width
             * character */
-           screen_cur_col = 9999;
+# ifdef FEAT_GUI_MACVIM
+           if (*p_ambw == 'd' || !gui.in_use)
+# endif
+               screen_cur_col = 9999;
        }
        else if (utf_char2cells(ScreenLinesUC[off]) > 1)
            ++screen_cur_col;
```

**Comment by jordwalke** [comment]
Tested locally and it seems to solve the issue that you pointed out with `ambiwidth`. Thanks for the suggestion!

**Pull request merged**
