### PR TITLE
Move BLUR_TRANSPARENCY into its own file

### PR DESCRIPTION
**Pull request by rhendric**
... so that both Vim and MacVim can see it.

I broke my own feature when fixing the Leopard compilation issue, because I'm a dummy and didn't test the right thing. Sorry for the multiple pull requests. I didn't realize MacVim the separate application doesn't reference vim.h, so of course the #define can't be there.

### CODE REVIEW

**Comment by chdiza** [comment]
This PR works locally on ElCap.  Lemme try to build on Tiger real quick...

**Comment by chdiza** [comment]
Builds on Tiger.  I'll defer to others on merging.

**Comment by splhack** [comment]
ready to merge?

**Comment by rhendric** [comment]
If you're asking me, :+1:

**Pull request merged**
