### PR TITLE
Control sharing the find pasteboard with defaults

### LINKED ISSUE #501: Doing a search in MacVim changes the search string in Chrome ❗️
Doing a search in MacVim changes the search string in Chrome.

Steps:
In Chrome do cmd-f "foo"
In MacVim do / "bar" enter
Now in Chrome the search string is "bar".

This bug is very surprising and severe.

### PR DESCRIPTION
**Pull request by splhack**
`MMShareFindPboard` default is `YES`.

    $ defaults write org.vim.MacVim MMShareFindPboard -bool NO

Fix #501

### CODE REVIEW

**Comment by tobireif** [comment]
Thank you all!

**Comment by tobireif** [comment]
Oh, I thought it will be disabled by default, and those who want the old behaviour could switch it on.

@jpetrie wrote in #501:
"We could potentially disable this, but it would need to be a defaults setting, since some people do like this behavior."

This is what I want - disable the strange behaviour where searching in MacVim using "/" affects other apps. (This behaviour is so unexpected and potentially problematic that it needs to be disabled.) Those who know about this strange feature and do want it can then enable it.

**Comment by jpetrie** [comment]
Whenever a new setting is introduced, there will always be divided opinions over what the default should be.

In general I think the best way forward is to preserve existing behavior with new defaults as much as possible; it creates a more consistent experience along upgrade paths, and it's statistically the thing more users are likely to expect (especially as the behavior in question ages without reports of defects, as in this case). This is especially true of behavior that is part of the OS parlance, as this find-pasteboard-sharing is.

**Comment by chdiza** [comment]
Thanks for this.

Unfortunately it appears to have a bad side-effect.  For instance, if I do Cmd-F in Safari to search for "foo" in the open webpage, then exit the search feature with the escape key, then open up MacVim, then in MacVim do `/BAR<CR>`, then go back to Safari, then do Cmd-F again, what I *should* see is "foo" in Safari's search bar.  Instead I see a blank.

This is probably better than the old behavior, which was to see "BAR" in Safari's search bar.  But it's not much better.  Now the user has to re-type their old search string.

It is as if, instead of altogether avoiding the OS-wide "search string" stuff, MacVim is *clearing* it.

Perhaps I'm wrong about what the expected behavior should be.

**Comment by tobireif** [comment]
@jpetrie So I'll run this:
```
defaults write org.vim.MacVim MMShareFindPboard -bool NO
```

@chdiza Perhaps best to submit a new issue report?

**Pull request merged**
