### PR TITLE
Fix spacing issues on ligatures as seen on #36.

### PR DESCRIPTION
**Pull request by Shirk**
This PR is a response to the new issues reported in #36, currently WIP - see checklist below.

The idea is to do a proper analysis of the ligatures (if any) and try to avoid double character draws / moving spaces etc.

code changes:
- [x] compare string with- and without ligatures
- [x] skip positions as needed
- [x] add compatibility with emoji
- [x] add a note to the preference to indicate the `cursorline` / `relativenumber` requirement.

testing:
- [x] instruments: no leaks?
- [x] local test with and without listchars
- [x] local test with and without cursorline (to force / relax draws)
- [x] collect feedback from affected users (see #36)

### CODE REVIEW

**Comment by splhack** [comment]
Unfortunately, ligature support breaks Emoji rendering. Surrogate pairs, perhaps?

ligature_disable

ligature_enable

**Comment by Shirk** [comment]
That feature got in after my first PR - I'll have a look at it..

**Comment by Shirk** [comment]
@splhack - looks like the fault isn't related to this new PR..
Stock MacVim (with ligatures enabled) has the same problems with the way surrogate pairs are handled.
I'm slightly inclined to reopen your PR #65 by adding a note that this wasn't tested to work with ligatures enabled.

**Comment by Shirk** [comment]
@splhack - I think I have something working for both of us:

emoji and ligature sample

**Comment by splhack** [comment]
@Shirk :+1:

**Comment by jordwalke** [comment]
The result of this diff is that MacVim has a reasonable user experience for ligature fonts if you have `cursorline` enabled.  There are still remaining issues being tracked, but I can confirm that this fixes bugs that were currently already merged into `master`.

**Comment by jordwalke** [comment]
Any update on this?

**Comment by Shirk** [comment]
@jordwalke  - I'm undecided.. 

I could remove the [WIP] for this part and convince @douglasdrumond to merge but it would still only work for people with either `cursorline` or `relativenumber` enabled.

So I'm debating with myself whether to add a notice to the option dialog (*"currently cursorline or relativenumber setting is required for this feature"*) or go looking for a way to get vim to always redraw the active window when it has ligatures enabled. 

I've been looking around the MacVim-gui design and there seems to be no easy for the GUI process to communicate to the back-end process that the active (VIM)window needs redraw.

**Comment by jordwalke** [comment]
My justification for suggesting this be merged is that it fixes bugs that are in master and seems to not make anything else worse. Of course, I'd love for everything to be redrawn at the right time perfectly with or without `cursorline`. But there are many people who would do anything for ligatures. For those people, with this implementation, it's pretty easy to add a little tweak to their `vimrc`:

```vim
set cursorline
highlight CursorLine guibg=NONE
```
Not to downplay how awesome it would be for this to not be necessary.

**Comment by chdiza** [comment]
What will happen if someone does not want ligatures rendered, does not have a font with ligatures, but has `cursorline` or `relativenumber` enabled?  Is their experience going to be bogged down with constant redraws?  If so, then this should either not be merged, or their needs to be a checkbox in the prefs, OFF by default, to enable this ligature stuff.

**Comment by jordwalke** [comment]
screen shot 2015-11-13 at 11 30 11 am


There is certainly an option (already in master, in fact) - @Shirk will have to confirm that it actually has no impact when toggled off - but I can't even detect a perf impact when toggled *on* (on my very weak macbook).

**Comment by Shirk** [comment]
@chdiza - not sure if you're using a current snapshot or not but ligatures have been merged already and have absolutely no impact at all since they are in no way related to `cursorline` or `relativenumber`. The only relation between them is that if you happen to have enabled `cursorline` or `relativenumber` ligatures will be displayed properly since in that case ViM will always redraw the whole current line if the cursor moves up / down (*which is not new but the default behavior since both options require the line to be redrawn*).

**Comment by Shirk** [comment]
@jordwalke for now I'm going with the "add a note the preferences" way so this PR has a chance of getting merged quickly.

@douglasdrumond - if you wouldn't mind to have a look.

**Pull request merged**
