### PR TITLE
Merge with Vim 7.4.854

### PR DESCRIPTION
**Pull request by splhack**
This merge seems big and scary. I merged vim/master branch from the Vim repository, git@github.com:vim/vim.git . It is totally different commits from macvim/vim branch which has been used for merging with Vim source code to MacVim. That's why this pull request seems big. But the next time, we can just do `git merge vim/master` from the Vim repository.

    # I did
    $ git remote add vim git@github.com:vim/vim.git
    $ git fetch vim
    $ git merge vim/master
    # merged a lot of files manually...
    $ git commit

    # created diff between macvim/master (7.4.769) and HEAD
    $ git diff b93cc077ea36594e44b5f98e1c76e19288ea809a..HEAD > /tmp/x0.diff
    # created diff between 
    $ git diff v7-4-769..vim/master > /tmp/x1.diff
    # checked /tmp/x0.diff /tmp/x1.diff, no significant changes.

### CODE REVIEW

**Comment by splhack** [comment]
> the next time, we can just do git merge vim/master from the Vim repository.

See, easy to merge.

    $ git remote show vim
    * remote vim
      Fetch URL: git@github.com:vim/vim.git
    ...

    $ git fetch vim
    remote: Counting objects: 10, done.
    remote: Compressing objects: 100% (5/5), done.
    remote: Total 10 (delta 4), reused 4 (delta 4), pack-reused 1
    Unpacking objects: 100% (10/10), done.
    From github.com:vim/vim
       b58988b..a09a2c5  master     -> vim/master
     * [new tag]         v7.4.856   -> v7.4.856
     * [new tag]         v7.4.855   -> v7.4.855
    
    $ git merge vim/master
    Auto-merging src/version.c
    Merge made by the 'recursive' strategy.
     src/gui_gtk_x11.c |  4 ++--
     src/move.c        | 10 ++++------
     src/version.c     |  4 ++++
     3 files changed, 10 insertions(+), 8 deletions(-)

**Comment by amadeus** [comment]
I think this is probably a pretty bad way to do it, since it ends up duplicating most of the commits?

On my own personal macvim fork I just simply use cherry-pick with a range to to merge things in quickly and easily.

```
git cherry-pick 9534680^..b860388
```

It's an inclusive range - so `9534680` would be the first new commit, and `b860388` would be the latest commit on.

**Comment by splhack** [comment]
It doesn't break anything and I fixed several merge misses that were happened by the cherry-pick way. why it's bad way? duplicating commits will cause problems?

**Comment by splhack** [comment]
Just in case, I'm going to reconstruct `macvim/master` branch based on https://github.com/vim/vim/tree/master. It allows to git-merge using vim/master without duplicate commits. The macvim commits history are preserved as well.

**Comment by douglasdrumond** [comment]
Thanks, thanks, thanks

**Pull request merged**
