### PR TITLE
'guitablabel' should only be set if user hasn't set it in vimrc.

### PR DESCRIPTION
**Pull request by ychin**
Right now, the user has to override 'guitablabel' in gvimrc instead of vimrc because MacVim overrides the setting, but this change makes it so that MacVim only sets the defaults if the user hasn't set it already.

### CODE REVIEW

**Comment by chdiza** [comment]
I would have thought that `gvimrc` and not `vimrc` is where settings governing the GUI should go.

**Comment by chdiza** [comment]
In other words, what is the problem with having to override `guitablabel` in `gvimrc`?  That's where one would expect to override it.

**Comment by ychin** [comment]
That's the best practices as described in the docs (gui.txt), yes, but I think there are people who also just set gui options in vimrc using `has("gui_running")` checks. Feels to me if the user has already set the option, MacVim's own gvimrc should try to respect that and not stomp the custom value (you can set this option in regular Vim/Gvim's `vimrc` and it will work, for example).

My understanding of `gvimrc` is that there are certain GUI work and initialization that happens after `vimrc` is sourced, which is why you need another file, but in this case there's no technical limitation on why we should stomp the user's provided value.

**Comment by ychin** [comment]
Oh actually, I made a mistake in the docs then. You need to still override the `gvimrc` to get the default tab labels back. I'll submit PR for that.

**Comment by chdiza** [comment]
> but I think there are people who also just set gui options in vimrc using has("gui_running") checks.

There are (though I suspect it's very few), but they're not supposed to be doing that.

I don't see the point of this unless one is desperately trying to avoid needing to have a `~/.gvimrc` in the first place.  If you already have a `~/.gvimrc`, there is no reason not to put your `guitablabel` setting in it, and there is no reason to put that setting in `~/.vimrc`.

> Feels to me if the user has already set the option, MacVim's own gvimrc should try to respect that and not stomp the custom value

This would be true for options that have nothing to do with the GUI (e.g., `&textwidth`).  But I can't see why that shouldbe presumed to hold for GUI specific options.

**Comment by ychin** [comment]
Hmm, I don't really have too strong an opinion of this. I do think it's nice to respect options that was set in vimrc if the user set it somehow but yes they should have been set on the gvimrc instead. There are also other existing `vimrc` settings you can set like `macvim_skip_colorscheme` in order to not having to override them in gvimrc. Pinging @splhack  in case he has an opinion on this.

**Comment by splhack** [comment]
I don't have any opinion about that :) and I can revert it #637

**Pull request merged**
