### PR TITLE
Merge vim/master

### PR DESCRIPTION
**Pull request by chdiza**

### CODE REVIEW

**Comment by chdiza** [comment]
I'm making this a PR because for some reason my writing privileges to our repo have vanished.  On the organization page I'm now listed as a "member" not a "collaborator".

Is this on purpose?  I received no notification of this from GitHub, unlike when I was made a collaborator by @douglasdrumond.

**Comment by splhack** [comment]
you really don't need to create a pull request for merging vim/master, just wait a bit, it would be updated.

**Comment by chdiza** [comment]
> you really don't need to create a pull request for merging vim/master, just wait a bit, it would be updated.

As my previous comment indicated, I'm supposed to not *have* to make a PR.  Does nobody, @jpetrie, @douglasdrumond  know what happened to my collaborator/repo-writing status?

**Comment by chdiza** [comment]
Wait, something weird is going on.  Why are there comments in this PR from really old PRs not made by me?

**Comment by splhack** [comment]
@chdiza sorry, in terms of quality of code, you don't qualify to have write permission on this repository.

**Comment by chdiza** [comment]
> sorry, in terms of quality of code, you don't qualify to have write permission on this repository.

It was incredibly rude to just lock me out without telling me this beforehand, or immediately afterwards.

**Comment by jpetrie** [comment]
I'm confused, @splhack. Was there are particular event -- some extremely negligent commit or inappropriate conduct towards some other user -- that led to this? Some of the comments @chdiza made towards @Shirk in some of the referenced commits above seem a bit blunt, but I'm not sure *that* is a good reason to summarily remove his commit access without warning? What's going on here?

**Comment by chdiza** [comment]
> Was there are particular event -- some extremely negligent commit

I haven't actually written any code for this repo, except for one very small piece that he told me to write, and a tweak to `mvim` from before any of us were made maintainers.  I think he thinks that because I don't know C I will mess up the repo.  I don't know why he thinks that I would make some change to the C portions and then push it without consulting anyone.

**Comment by splhack** [comment]
@jpetrie I don't know what's going on this pull request, but this tragedy is enough reason of no-write permission for awhile. first of all, I don't know the reason chdiza has write permission of this repository in the first place. not enough pull requests or patches of MacVim, the few patches were just only for shell script not including Objective-C and C, actually I was not able to accept several pull requests due to the quality so far, lack of knowledge of git "I'm not sure if I did this right" https://github.com/macvim-dev/macvim/pull/161#issuecomment-161377079, etc.

**Comment by splhack** [comment]
@chdiza I'm sorry the reason of without telling you is that you don't have email addresses on the github profile page https://github.com/chdiza

**Pull request closed without merging**
