### PR TITLE
Update gui_mac.txt headings

### PR DESCRIPTION
**Pull request by dkav**
Update gui_mac.txt headings to match MacVim release.

### CODE REVIEW

**Comment by ychin** [comment]
Hi, thanks for the PR. Just left a couple feedbacks.

**Comment by dkav** [comment]
@ychin no feedbacks visible on my end.

**Comment by ychin** [comment]
It's in the code review section. First one was that I didn't feel that it's necessary to include the release number, and the second is that I think we should just called this "MACVIM REFERENCE MANUAL".

**Comment by dkav** [comment]
Nothing showing (see screenshot). Either way I am happy to go along with your suggestions. You could remove the date too.
 
Screen Shot 2023-02-10 at 23 15 44

**Comment by dkav** [comment]
@ychin changes made as you suggested.

**Pull request merged**
