### PR TITLE
Support guioptions 'k' flag in MacVim, prevents unnecessary window re…

### LINKED ISSUE #617: Support guioption 'k' to avoid resizing window when adding tabs/vsplits/etc
Implement the new guioption 'k' introduced in https://github.com/vim/vim/commit/8ac441576fd219fb7227349e228d5b68520b204a. It attempts to avoid resizing the window while adding/removing the tab bar, toolbar, vertical splits. This is similar to how MacVim / Vim behaves when in fullscreen mode, and avoids the window keep resizing itself which is counter to how other normal text editors work.

I implemented the original pull request https://github.com/vim/vim/pull/703, and can submit a pull request for this. It will probably mostly be modifying MMWindowController.m's logic to support this new option.

### PR DESCRIPTION
**Pull request by ychin**
…size

Adds support for native GVim's 'k' flag. Adding/removing tabs/scrollbars
and setting 'linespace'/'columnspace' would now cause the number of
lines and columns in the buffer change to keep the window size constant,
instead of the other way round of resizing the window to keep the view
size constant. This helps prevent the window from resizing itself
unncessarily, which could be especially annoying when the window is
pinned/maximized.

Manually setting 'lines'/'columns', going to full screen, dragging the
window corner to resize would still resize the window.

Also removed misc calls within MMWindowController.m that were setting
shouldResizeVimView. Those calls were already handled by native Vim's
gui.c's gui_set_shellsize so it's redundant.

Close #617

### CODE REVIEW

**Comment by ychin** [comment]
I could quite find any unit tests specific to MacVim in the repo (raw Vim has the src/testdir which has a collection of Vim scripts for unit tests). If I missed that I can add unit tests for this functionality as well.

**Comment by ichizok** [comment]
@splhack @ychin 
It appears this change has caused #721, so I think should revert it once.
BTW, this guioptions-k does not work in my environment (using d0807a4aff9aebb34a982073a01294c45a0c4bc5).

**Comment by ychin** [comment]
Ok. Feel free to revert the change. I'll try to look into the issue and submit a proper fix. The way the messages got bounced when resizing windows involved quite a few roundtrips, and it's possible I missed some cases since I didn't test on another monitor.

**Comment by ychin** [comment]
Also @ichizok how does guioptions-k not work for you? Can you give a more detailed set of repro steps? I'm curious as it could be related why it's causing issues.

**Comment by ychin** [comment]
@ichizok  @splhack  Opened new pull request (#727) to revert this change. Sorry for the breakage.

**Comment by ichizok** [comment]
**Repro steps**

Start MacVim with GUI:
`/path/to/MacVim.app/Contents/MacOS/Vim --clean -g`

Set `guioptions-k` and then `guioptions-T` (add toolbar):
```vim
:set go+=k
:set go+=T
```

Expected: Shows toolbar, and window size (height) does not change.
Actual: Shows toolbar, and window height increases by toolbar height.

MacVim:
 
guioptions-k-mac

My understanding is that the following GVim (linux) is the correct behavior.
With `guioptions-k`, the window height does not change by showing/hiding toolbar.

GVim (on Ubuntu):

guioptions-k-linux

**Comment by ychin** [comment]
Ah yes, right. I think there's actually a bug in that toolbars don't work, but scrollbars / linespace / tabs do work. I will fix that case as well in the second version of this pull request later.

**Pull request merged**
