### PR TITLE
Update icon to macOS 11 style

### PR DESCRIPTION
**Pull request by jasonlong**
Way back in #1, I submitted the currently used app icon for the then-new Yosemite version of OS X. The new icon styling for Big Sur is a pretty big departure from the current styling and it makes sense to have MacVim continue to feel current going forward (once macOS 11 ships).

This PR includes a new `MacVim.icns` that looks like this:

### Option 1

I didn't include any document-specific `.icns` files because I read the following on [this page](https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/), but I'm happy to help generate them if I'm misinterpreting.

> To compose a document icon, the system combines your app icon with the familiar folded-corner icon shape.

### CODE REVIEW

**Comment by jasonlong** [comment]
Here's an alternative version that aligns with the original icon better. 

Icon-512

**Comment by ychin** [comment]
Thanks for the update! Between the original and alt version is there one you prefer?

I appreciate the update but I may let this sit a little bit when macOS 11 Big Sur is still in beta to see if others have opinions and let me take a look at Apple's guidelines in the meantime.

**Comment by jasonlong** [comment]
Sounds good @ychin. I think it makes sense to gather more feedback during the Bir Sur beta period so that everyone feels confident by the time the macOS 11 ships.

I initially liked the first version better, but after refining the [second version](https://github.com/macvim-dev/macvim/pull/1054#issuecomment-653912016) more I prefer that one. Since it stays more true to the original Vim logo, that's probably the more sensible (and least controversial) direction.

**Comment by ychin** [comment]
Just some immediate feedback / thoughts: I like [option 1](https://github.com/macvim-dev/macvim/pull/1054#issue-444342038) better. The second option aligns better with the original Vim logo but it looks… kind of off? Like we just introduced a white squircle border for no good reason with yet another solid color border inside it. It in a way reminds me of Vim in that we pile on new features but trying to keep backwards compatibility at all cost, but seems like at first glance at least the first icon seems cleaner.

The other thing that jumped at me was how strong the 3D shading shadow is. The drop shadow is fine, but the "V" almost feels too… 3D to me. I'm still not sure if I'm put off by it itself or just the new Big Sur aesthetics, and I'm going through the [list of icons](https://www.cultofmac.com/715717/fantastic-fugly-all-new-app-icons-macos-big-sur/) and the [official recommendation](https://developer.apple.com/design/human-interface-guidelines/macos/overview/whats-new-in-macos/) to see how this fits in, and so far it seems… inconclusive to me and seems like some icons have this strong 3D shading effect (e.g. Messages, App Store) while others still look flat with a squircle around the icon (e.g. Apple TV, Apple Music). So I'm not sure yet.

Maybe will need to wait till I get a beta version installed and can try them side-by-side.

**Comment by jasonlong** [comment]
Here's another variant on the first option, but with the shading dialed way down.

### Option 3

**Comment by eirnym** [comment]
I perfect the most Option 2. I like that macOS is going back to 3d effects in icons

**Comment by jasonlong** [comment]
### Option 4

**Comment by UncleBill** [comment]
👍  for Option 2 but with the shading dialed way down == Option 4 with white background color.

**Comment by jasonlong** [comment]
Sorry for the delay - I was on vacation last week.

### Option 5

**Comment by ychin** [comment]
Hi, @jasonlong , do you mind if you could provide all the different options' `icn` files? I am trying to look at them in Big Sur beta just to be able to tell how they look like relative to the other icons, and it would be easier if you could provide the icns either in individual commits or just another way to attach them. Thanks!

**Comment by ychin** [comment]
Just pinging again. @jasonlong , do you mind providing the different options as `icn` files?  I would like to try them out in macOS 11 beta to see what they look like if possible.

**Comment by jasonlong** [comment]
@ychin Sorry for the delay. Here's a link to the different `.icns` options:

https://macvim-icns-riselanjk.vercel.app/

**Comment by ychin** [comment]
Just trying out to see how the 5 options look relative to the other icons in the Big Sur beta:

Option 1:

MacVim Dock icn 1

MacVim Dock 2 icn 1

---

Option 2:

MacVim Dock icn 2

MacVim Dock 2 icn 2

---

Option 3:

MacVim Dock icn 3

MacVim Dock 2 icn 3

---

Option 4:

MacVim Dock icn 4

MacVim Dock 2 icn 4

---

Option 5:

MacVim Dock icn 5

MacVim Dock 2 icn 5


---

After seeing it side-by-side, I think I'm still not a huge fan of Option 5 (even though it seems to be popular with the limited voting we have). In particular, most default icons seems to have a simple "background color + thing in the middle" design, where as Option 2/5 is a thing within a thing within a thing. But I feel like Option 5 looks a little better in the 2nd screenshot (next to the Home app) compared to the first one.

I think Option 3 remains my favorite, whereas I think Option 4 really doesn't stand a chance.

Also, Apple seems to not be terribly consistent in their 3D shading effect. App Store / Messages' icons use a fairly strong shading effect, but Music / News look pretty flat. [The official HIG guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/) only suggests using it so 🤷 .

@jasonlong what do you think? Which one do you personally think look the best?

---

Going to do a second round of voting below. Feel free to both vote up or down on more than one icon! Kind of doing a poor-man's approval/ranked voting this way.

**Comment by ychin** [comment]
Vote Option 1:



MacVim Dock icn 1

MacVim Dock 2 icn 1

**Comment by ychin** [comment]
Vote option 2



MacVim Dock icn 2

MacVim Dock 2 icn 2

**Comment by ychin** [comment]
Vote Option 3



MacVim Dock icn 3

MacVim Dock 2 icn 3

**Comment by ychin** [comment]
Vote Option 4



MacVim Dock icn 4

MacVim Dock 2 icn 4

**Comment by ychin** [comment]
Vote Option 5



MacVim Dock icn 5

MacVim Dock 2 icn 5

**Comment by jasonlong** [comment]
Thanks for putting these comparisons together @ychin. 

> Apple seems to not be terribly consistent in their 3D shading effect.

Agreed, this has made these explorations challenging trying to align the treatment w/ the default icons. 

> I think Option 3 remains my favorite

Seeing them all in context, I tend to agree with you. Sometimes I feel like that one is _too_ flat, but I feel like that one looks better than the really shaded Option 1. If we want to try some shading options in-between, I'm happy to build some.

**Comment by bingobongo** [comment]
The _V_ a little further to the right?

v3-bit-right

**Comment by jasonlong** [comment]
@ychin With Big Sur out, can I help at all getting the icon update ready to ship? I can update this PR to use Option 3 above if you like.

**Comment by ychin** [comment]
@jasonlong Yes please update to Option 3. I was a little busy with work and got a little behind on making sure MacVim is ready for Big Sur!

Just to make sure https://github.com/macvim-dev/macvim/pull/1054#issuecomment-703696158 is addressed. I personally think the alignment in the original Option 3 looks fine, but it's because of how the "V" looks in the font that it looks a little offset to the left. I think it's fine to leave it as is, but if you want to shift it to the right I'm fine with that too.

**Comment by jasonlong** [comment]
Ok, the branch has been updated here and I tried to better optically center the mark in the container. The final version looks like this:

MacVim logo

**Comment by ychin** [comment]
Merged! Thanks for the update.

**Comment by diogocampos** [comment]
I know this issue is closed, but I'd like to suggest something like the "overhang" versions proposed for VS Code in [this comment](https://github.com/microsoft/vscode/issues/101014#issuecomment-654350838), maybe with the bottom and/or the right tip of the _**V**_ sticking out a bit from the squircle.

Sadly I don't have the design skills to mock that up. Would anyone care to take a shot at it?

**Comment by ychin** [comment]
Hi, I appreciate the comment but I'm not sure I'm buying the overhang design. Also, the Vim's "V" has always been level at the top, so to make it overhang you would have to change the iconography of it as well to have some part poke out. I think the overhang is usually designed for an object laid on top of the squircle, not for a letter (https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon).

If you have more thoughts though feel free to discuss at https://github.com/macvim-dev/macvim/discussions/1140 since people love to discuss design changes :) .

**Comment by eirnym** [comment]
Ps: the default icon is highly new for me and an icon in docker looks very different than on a GitHub page. 

I love the diamond was before and new icon looks flat to me. 

Is it possible in macOS to change an icon from app settings like I can do it in iOS? 

If yes, is it possible to add all icons and let user decide which icon to show? I somewhat want an option, to decide.

**Comment by ychin** [comment]
@eirnym See the discussion on https://github.com/macvim-dev/macvim/discussions/1140 (we should focus on using that thread to discuss icon change). No, macOS doesn't allow for multiple icons for an app so it has to be one. You *could* change it yourself in Finder and the OS will remember it, but we don't have a way for MacVim to bundle multiple icons and let you choose, unfortunately.

With most things icon or interface change related, I think it takes time to adapt. I'm open to see how the new icon is received in a couple more weeks at least to see if people got used to it.

**Comment by eirnym** [comment]
@ychin Thank you for a link and an information. Here I wanted to ask a technical question, not discuss my personal preferences, and you gave me a good answer.

**Comment by timoxley** [comment]
## For anyone arriving in this thread wanting to say that they hate the new icon

I hated it 24 hours ago, but now? Looks fine. Whatever. Just give it a few days.

**Comment by samusz** [comment]
@ychin  I use `brew` to install macvim.  (as a formula in HomeBrew parlance/terminology) with `brew install macvim` 
(and update to the last version with `brew upgrade macvim` )

Here I won't discuss homebrew's merit.
I just wanted to point out that it may be possible to have an option in `brew` to get alternate icons as I believe have seen this for another app in brew... (can't  remember which) This could be a workaround to MacOS 11 BigSur limitations ? 

I'll try to get some time to investigate this (as I am not a brew wizard)

**Comment by ychin** [comment]
Homebrew doesn't build from source by default. It builds a default bottle that you download from their server, so this would only be an option if you build MacVim from source using Homebrew, and I think that's just too niche an option.

**Comment by eirnym** [comment]
@ychin this option exists in MacPorts and I'd like to see it. In home-brew it was cutoff as they have a policy to support only one configuration. 

PS: I have questions on MacVim to provide better support in MacPorts

**Comment by ychin** [comment]
What would MacVim need to do to support MacPorts better? I used to use MacPorts but moved away from it, and it seems like MacPorts usually falls behind MacVim releases by a couple versions (https://ports.macports.org/port/MacVim/summary). Looking at metrics on that (which to be fair I don't know how accurate that i), it also appears the usage is quite low, which is why I'm not sure if I want to spend too much time supporting it (homebrew-core's MacVim formula is maintained by Homebrew themselves).

Anyway let's make a new issue if you want to add more support for MacPorts, which I'm not against. I do question if it's worth spending effort to make the icon customizable just for MacPorts though. It's a pretty niche within niche use case.

**Comment by eirnym** [comment]
I want to take maintainership of MacVim in MacPorts

**Comment by ychin** [comment]
macvim-dev doesn't own the MacPorts definition. You may want to go to https://ports.macports.org/port/MacVim/summary and ask the maintainer instead.

FWIW I don't particular support having customizable icons for the reasons I already discussed (majority of users would not be installing MacVim in a way that supports icon customization, and also I don't really think that's good for help identifying the app if we give too many icons to choose from).

**Comment by oseiberts11** [comment]
"it seems like MacPorts usually falls behind MacVim releases by a couple versions"

maybe that explains why I just recently got the new icon...
I'm not sure why a new icon was needed, but now it looks imho totally out of place with the Vim icons on my other computers. It hardly looks like Vim at all, really. Where did the "im" go? Was that really needed to drop it?

**Comment by jasonlong** [comment]
@oseiberts11 The "im" has been part of the MacVim logo for a long time ([at least 6 years](https://github.com/macvim-dev/macvim/pull/1)).

**Comment by oseiberts11** [comment]
Interesting, you're right! I guess that the change somehow made it more "in my face" :)

**Comment by ychin** [comment]
Also, are you using macOS 11 Big Sur @oseiberts11 ? If you are, I would be surprised if you find the old icon preferable to the new one. If you aren't, unfortunately, as been discussed on this thread already, there isn't an easy way to support multiple icons, and as a project we should be supporting the latest macOS versions as top priority while remaining backwards compatible with older versions.

**Comment by oseiberts11** [comment]
@ychin No, I don't (yet). Company policy has not approved it yet, I think... So this is on my work computer, that's why I notice that the icon differs so much from other Vim versions, because for my personal use I use the generic Unix version of Vim with GTK GUI.

**Pull request merged**
